name: Auto Renew Ugeen
on:
  schedule:
    - cron: '0 5 * * *' # يشتغل يومياً الساعة 5 فجراً
  workflow_dispatch: # زر لتشغيله يدوياً في أي وقت

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Script
        run: python script.py
