name: Update Ugeen Playlist

on:
  schedule:
    # سيتم التشغيل تلقائياً كل 6 ساعات
    - cron: '0 */6 * * *'
  workflow_dispatch: # يتيح لك تشغيل التحديث يدوياً للظغط على زر Run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Update Script
        run: python update-ugeen.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Update activation code" || exit 0
          git push
