name: Auto Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - set up python:
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - install requests:
        run: pip install requests
      - run script:
        run: python run.py
      - commit:
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add playlist.m3u
          git commit -m "Update Playlist" || exit 0
          git push
